### ISSUE TITLE
Дизайн меню

### ISSUE THREAD

**Issue by gregguh** [osanwe/Kat#14]
Склепал дизайн-концепт для меню

![default](https://cloud.githubusercontent.com/assets/11874993/9835837/d99473ea-5a06-11e5-80d5-a70fdc512dbd.png)

**Comment by osanwe** [comment]
Принято :)

![screenshot-14-09-15-11-57-58](https://cloud.githubusercontent.com/assets/3856993/9844890/00906ea0-5ad8-11e5-8788-8c3421dea1db.png)
