### ISSUE TITLE
А что насчет использования библиотеки vreen для работы с vk.api?

### ISSUE THREAD

**Issue by alekseysidorov** [osanwe/Kat#2]
Когда-то давно для N9 начинал пилить клиент, он был разделен на ui и библиотеку для работы с vk.api. Либа умеет базовые вещи и достаточно легко расширяется. В том числе прямо из qml'а. 

Я сам ей сейчас уже не занимаюсь практически, но могу оказать поддержку и добавить в неё некоторый нужный функционал. 
https://github.com/gorthauer/vreen

**Comment by osanwe** [comment]
В интеграцию C++ и QML я ещё не сильно углублялся. После беглого просмотра исходников vreen мне показалось, что взаимодействие QML с C++ не такое прозрачное, как с JavaScript. Как я понял, для связи QML и C++ требуется создание плагина, который в дальнейшем будет подключаться к проекту. Для этой цели создал ветку dev-vreen - так что при желании её можно использовать для экспериментов в данной области.

**Comment by alekseysidorov** [comment]
Либу я делал в том числе для использования из плюсов. К тому же плюсы быстрее работают и больше могут.
Чую самым проблемным будет авторизацию переделать. Там есть вшитый ключ для прямой. Вполне вероятно пока его хватит, но в будущем ее возможно придется переработать.

**Comment by alekseysidorov** [comment]
Да через плагин. На jolla с этим нет проблем?

**Comment by osanwe** [comment]
> На jolla с этим нет проблем?

Как я писал, в использование C++ в связке с QML не вдавался. Если судить по блогам, посвященным разработке под Sailfish OS, то проблем вроде как нет.

> Чую самым проблемным будет авторизацию переделать.

Этим, я думаю, можно не заниматься. После авторизации получаемые данные храняться в БД vkFish (забыл переименовать - к следующему релизу будет исправлено на harbour-kat).
