### ISSUE TITLE
Дизайн меню

### ISSUE THREAD

**Issue by kreopt** [osanwe/Kat#7]
Предлагаю сделать его не отдельной страницей, а выдвигающимся меню. Как это сделано, например, в андроид-версии.
![d30d0bef1df562eac17823f28651f3b7](https://cloud.githubusercontent.com/assets/3601472/8639075/25ba75f8-28e8-11e5-9cc4-a5bbbf4864e2.png)
Главной страницей же оставить новости. Перелистывание вправо = диалоги.

**Comment by osanwe** [comment]
1. Боковую панельку, да, можно.
2. По поводу двух страниц. Удобнее будет сделать начальную настраиваемой и отображать только её одну.

**Comment by osanwe** [comment]
Сделал набросок бокового меню через Drawer: https://github.com/osanwe/Kat/blob/f72c14ec6040935684bcadf7839a284f2d779918/qml/pages/NewsFeedPage.qml

**Comment by kreopt** [comment]
У меня в ветке сделана начальная реализация меню. Думал на выходных доделать. Для таких штук прям вообще подходит DockedPanel.

**Comment by kreopt** [comment]
хотя Drawer смотрю - тоже подходит, вроде

**Comment by osanwe** [comment]
Можно сделать два билда и сравнить.

**Comment by kreopt** [comment]
Щас, к сожалению, очень много работы, поэтому свой билд доделывать не буду. Оставлю как затравку для дальнейшего рефакторинга(лучше вынести эту панель в отдельную компоненту и использовать ее на каждой странице одной строчкой).
Что касается самой панельки, мне кажется имеет смысл переместить ее вправо и добавить кнопку открытия(ровно так, как это сделано в приложении whatsup). Это более логично, на мой взгляд, т.к. на sailfish свайп вправо - это либо отмена действия, либо возврат назад. А вместо этого открывается меню. Если же рассматривать свайп влево(да еще и кнопочка, чтоб видно было, что это можно делать) - это либо какие-нибудь подробности, либо действия. Здесь меню более уместно

**Comment by osanwe** [comment]
В клиенте WatsUp используется элемент DockedPanel. Его использование оправдано только если выносить на него еще какие-либо элемены.

![](https://openrepos.net/sites/default/files/packages/184/screenshot-20150617092035.jpg).

В реализации, предложенной мной, боковое меню имеется только у корневых страниц, таких как список новостей, список диалогов и т. д. При переходе глубже оно отсутствует.

Также для реализации бокового меню использовал отдельную страницу, в которой меняются foreground элементы. Подробнее описывал здесь: http://osanwe.quora.com/Weekly-digest-1-2015-07-18-2015-07-25

**Comment by gregguh** [comment]
Лучше его сделать отдельной страницей, как, например, реализованы категории в магазине.

**Comment by osanwe** [comment]
@gri4994: Пожалуй соглашусь. Для постоянного использования боковое меню и выходит за пределы концепции дизайна ОС, и не является достаточно удобным. Предлагаю на этом закрыть обсуждение данного вопроса: https://www.youtube.com/watch?v=JN9Zb9J7yg4
